import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";

const amsterdamFont = localFont({
  src: "./fonts/amsterdamtwottf-ovmee.ttf",
  variable: "--font-amsterdam-two",
  weight: "400",
});
const captCarnaval = localFont({
  src: "./fonts/captcanaveral.ttf",
  variable: "--font-cap-carnaval",
  weight: "900",
});

const glacialIndifference = localFont({
  src: "./fonts/GlacialIndifference-Regular.otf",
  variable: "--font-glacial",
  weight: "400",
});
export const metadata: Metadata = {
  title: "Restaurante Grama",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${amsterdamFont.variable} ${captCarnaval.variable} ${glacialIndifference.variable} antialiased bg-transparent`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
